let audios = ["zenek/Trabant.mp3",
"zenek/Magna Cum Laude - Pálinka Dal.mp3",
"zenek/Hungária_ Micsoda buli.mp3",
"zenek/KFT - Balatoni nyár.mp3",
"zenek/KFT - Afrika.mp3",
"zenek/Republic - Szállj El Kismadár.mp3",
"zenek/Magna Cum Laude - Színezd újra (Dalszöveg).mp3",
"zenek/Fenyő Miklós   Csavard fel a szőnyeget.mp3",
"zenek/TNT - Titkos üzenet.mp3",
"zenek/Neoton Familia - Santa Maria.mp3",
"zenek/Pierrot - Ha sírni látod a bohócot.mp3",
"zenek/Petőfi Sándor_ Nemzeti dal.mp3",
"zenek/Edda_A kor kozepen.mp3",
"zenek/Beatrice - Azok a boldog szép napok.mp3",
"zenek/Ham Ko Ham  Ellopták a biciklim.mp3",
"zenek/P.Mobil - Kétforintos Dal.mp3",
"zenek/Rapülők - Tíz év vagy száz (Riszájkling 2006) (HQ).mp3",
"zenek/WELLHELLO - APUVEDDMEG - OFFICIAL LYRIC VIDEO.mp3",
"zenek/Neked írom a dalt.mp3",
"zenek/Sorsvonat - Digital Scream.mp3",
"zenek/Nagy Feró és a Beatrice - 8 óra munka (Official Audio).mp3",
"zenek/4S Street - Mesélek a bornak (Official Video).mp3",
"zenek/Azahriah - kapu.mp3",
"zenek/Follow The Flow - Nem tudja senki [OFFICIAL MUSIC VIDEO].mp3",
"zenek/Bagossy Brothers Company  - Olyan Ő (Official Video).mp3",
"zenek/DR BRS X Fekete Vonat feat. Halott Pénz - Hol van az a lány (Official Music Video).mp3",
"zenek/filo x apu - seholse.mp3",
"zenek/United - Csak egy szó.mp3",
"zenek/KOWALSKY MEG A VEGA- TIZENÖTMILLIÓBÓL EGY (OFFICIAL KLIP WERK).mp3",
"zenek/WELLHELLO - BARÁTOM - OFFICIAL MUSIC VIDEO.mp3",
"zenek/Compact Disco feat. Hősök - Minden rendben (Official Music Video).mp3",
"zenek/VALMAR ft. Szikora Robi - Úristen.mp3",
"zenek/Majka, Molnár Tamás - Azt beszélik a városban (OFFICIAL MUSIC VIDEO).mp3",
"zenek/Mindenki táncol 90' (Radio Edit).mp3",
"zenek/Omega - Gyöngyhajú Lány.mp3",
"zenek/Skorpió - Dédapám.mp3",
"zenek/Edda - Álmodtam egy világot.mp3",
"zenek/Hungária_ Isztambul.mp3",
"zenek/WELLHELLO - RAKPART - OFFICIAL LYRIC VIDEO.mp3",
"zenek/Kaukazus - Egyetlen szo (hivatalos klip).mp3",
"zenek/Ismerős Arcok - Nélküled.mp3",
"zenek/Kowalsky meg a Vega - Egy világon át (Official Video).mp3",
"zenek/Máté Péter - Egyszer véget ér.mp3",
"zenek/Majka & Pápai Joci - Mikor a test örexik (Official Video).mp3",
"zenek/Horváth Tamás_ Meggyfa (A Dal 2018 - Döntő).mp3",
"zenek/Curtis - Lehetne újra február (Official Music Video).mp3",
"zenek/Szabó Balázs Bandája - Bájoló.mp3",
"zenek/Halott Pénz - Élnünk kellett volna (feat Agebeat&Kovary).mp3",
"zenek/Bagossy Brothers Company  - Visszajövök (Official Video).mp3",
"zenek/Republic - A 67-es Út.mp3",
"zenek/Crystal - Te vagy a jel (Official Music Video).mp3",
"zenek/Follow The Flow - Anyám mondta [OFFICIAL MUSIC VIDEO].mp3",
"zenek/Ocho Macho - Jó nekem (official music video).mp3",
"zenek/Bereczki Zoltán & Szinetár Dóra - Lehetsz király.mp3",
"zenek/A Pál utcai fiúk - Mi vagyunk a Grund - hivatalos videoklip.mp3",
"zenek/Bereczki Zoltán - Kerek egész.mp3",
"zenek/Lotfi Begi x Burai - Háborgó mélység 2 (Official Music Video).mp3",
"zenek/Pápai Joci - Origo (Official Music Video).mp3",
"zenek/Kasza Tibi feat. Dér Heni - Ez annyira Te (Official Music Video).mp3",
"zenek/A SZŐLŐSBE - HORVÁTH TAMÁS (OFFICIAL MUSIC VIDEO).mp3",
"zenek/Máté Péter - Elmegyek.mp3",
"zenek/Ihász Gábor-Gyerünk srácok 1984.mp3",
"zenek/Neoton Familia - Don Quijote.mp3",
"zenek/KORDA GYÖRGY X BUDAPEST AIRPORT_ REPTÉR (official video).mp3",
"zenek/Republic - Erdő közepében.mp3",
"zenek/Republic - 16 Tonna Fekete Szén.mp3",
"zenek/Hungária - Csókkirály.mp3",
"zenek/Száll egy pofon a szélben.mp3",
"zenek/Emberek - Száz út.mp3",
"zenek/Első Emelet - Angyali Vallomás.mp3",
"zenek/Dzsungel Könyve - 03 - Beindul a pofonofon (Dés-Geszti).mp3",
"zenek/Dinamit - Tinédzser dal.mp3",
"zenek/Karthago - Requiem.mp3",
"zenek/Anna and the Barbies feat. Kiss Tibi_ Márti dala (official video) FULL HD.mp3",
"zenek/FLUOR  MIZU  OFFICIAL MUSIC VIDEO.mp3",
"zenek/Lord_ Vándor.mp3",
"zenek/Hobo Blues Band -Hosszúlábú asszony.mp3",
"zenek/Omega - Petróleum lámpa.mp3",
"zenek/Deák Bill Gyula- A Felszarvazottak Balladája.mp3",
"zenek/Koncz Zsuzsa Mr  Alkohol eredeti.mp3",
"zenek/Koós János, Esze Dóra   Sír a telefon.mp3",
"zenek/Quimby _ Don Quijote ébredése.mp3",
"zenek/Wellhello x Halott Pénz - Emlékszem, Sopronban (a Telekom VOLT Fesztivál himnusza).mp3",
"zenek/Tompos Kátya-Leperegnek az utolsó könnyek.mp3",
"zenek/Zorán - Apám hitte.mp3",
"zenek/Júlia nem akar a földön járni.mp3",
"zenek/Kiscsillag-Menetszél.mp3",
"zenek/Csik Zenekar - Te majd kezenfogsz es hazavezetsz [OFFICIAL].mp3",
"zenek/30Y - Felhő [Official Music Video].mp3",
"zenek/Szécsi Pál - Carolina.mp3",
"zenek/Neoton Familia - HOLNAP HAJNALIG.mp3",
"zenek/Máté Péter - Azért vannak a jó Barátok",
"zenek/Demjén Ferenc - Hogyan tudnék élni nélküled (Official Audio).mp3",
"zenek/Hooligans - Királylány (Official).mp3",
"zenek/EDDA művek - Kölyköd voltam.mp3",
"zenek/Ámokfutók - Robinson.mp3",
"zenek/Rúzsa Magdolna X Szakács Gergő - Kék a szívem [Official Video].mp3",
"zenek/PIRAMIS - Ha volna két életem - (Official Music Video) - 2006 Sportaréna  HD.mp3",
"zenek/MAJKA CURTIS BLR - BELEHALOK (OFFICIAL).mp3",
"zenek/Zoltán Erika- Szerelemre születtem (original video).mp3",
];
const numField = document.querySelector("#num")
const button = document.querySelector("#btn")
const zene = document.querySelector("#zene")
const aud = document.querySelector("audio")
const divid = document.querySelector("#divid")

button.addEventListener("click", onClick);

function onClick() {
    zene.textContent = "zene " + numField.value;
    console.log('Button clicked')
    console.log(audios[(numField.value - 1)%1000])
    aud.src = audios[(numField.value - 1)%1000]
    divid.classList = "zenenev"
}
